export const MOCK_ANALYSIS = {
  documentName: 'Employment Agreement - John Doe.pdf',
  contractType: 'Employment',
  safetyScore: 72,
  verdict: 'Needs Attention',
  verdictColor: 'caution',
  summary: 'This document contains several clauses that may limit your rights or impose unexpected liabilities.',
  stats: {
    safe: 18,
    caution: 5,
    unsafe: 3,
  },
  clauses: [
    {
      id: 'c1',
      number: '14.2',
      title: 'Non-Compete Agreement',
      risk: 'unsafe',
      originalText: '"...employee shall not engage in any competitive business activity within a 100-mile radius for a period of 5 years after termination..."',
      plainEnglish: 'After you leave this job, you can\'t work for any competitor within 100 miles for 5 whole years. That\'s basically saying you can\'t work in your field for a very long time, almost anywhere nearby.',
      legalNote: 'This clause is excessively broad in both duration (5 years) and geography (100 miles). In many jurisdictions, this would be considered unenforceable and could prevent you from working in your field.',
      section: 'Section 14',
    },
    {
      id: 'c2',
      number: '8.1',
      title: 'Intellectual Property Assignment',
      risk: 'unsafe',
      originalText: '"...all inventions, ideas, and software created by the employee during the term of employment, whether or not related to company business..."',
      plainEnglish: 'Anything you invent or create while you work here belongs to the company — even if you made it at home on weekends with no company resources. That app you\'ve been building? They might own it.',
      legalNote: '"Whether or not related to company business" is a predatory phrase. This would mean anything you build at home on your own time belongs to the employer.',
      section: 'Section 8',
    },
    {
      id: 'c3',
      number: '21.5',
      title: 'Termination without Notice',
      risk: 'unsafe',
      originalText: '"...employer reserves the right to terminate employment immediately for any reason at its sole discretion without severance or prior notice..."',
      plainEnglish: 'They can fire you at any moment, for any reason, with no warning and no pay. While "at-will" employment is legal in many states, zero severance for a senior role is unusual and concerning.',
      legalNote: 'This creates an extreme imbalance of power. While "at-will" employment is common, the lack of notice or severance for a senior role is atypical and high-risk.',
      section: 'Section 21',
    },
    {
      id: 'c4',
      number: '4.1',
      title: 'Mandatory Arbitration',
      risk: 'caution',
      originalText: '"...any dispute arising from this agreement shall be resolved through binding arbitration in accordance with AAA rules..."',
      plainEnglish: 'If you have a problem with the company, you can\'t take them to court. You have to go to a private arbitration process instead — which typically favors employers.',
      legalNote: 'Mandatory arbitration clauses limit your right to a jury trial. The outcome of arbitration is final and very hard to appeal.',
      section: 'Section 4',
    },
    {
      id: 'c5',
      number: '3.2',
      title: 'Confidentiality Scope',
      risk: 'caution',
      originalText: '"...employee agrees to maintain strict confidentiality of all information learned during employment, including but not limited to, technical, financial, and strategic information..."',
      plainEnglish: 'You must keep everything you learn at this company secret — forever. This is mostly standard, but the broad definition of "all information" could restrict you from using skills you develop here.',
      legalNote: 'Standard confidentiality is expected, but unlimited scope with no time limit is worth negotiating.',
      section: 'Section 3',
    },
    {
      id: 'c6',
      number: '7.1',
      title: 'Base Compensation',
      risk: 'safe',
      originalText: '"...employee shall receive an annual base salary of $120,000, payable bi-weekly in equal installments..."',
      plainEnglish: 'You\'ll earn $120,000 a year, paid every two weeks. This is clear, fair, and standard.',
      legalNote: 'This clause is clear and standard. No concerns.',
      section: 'Section 7',
    },
    {
      id: 'c7',
      number: '12.1',
      title: 'Vacation Policy',
      risk: 'safe',
      originalText: '"...employee is entitled to 15 days of paid vacation per year, accrued at a rate of 1.25 days per month..."',
      plainEnglish: 'You get 15 paid vacation days per year. You earn them gradually — about 1 day every month. This is reasonable and standard.',
      legalNote: 'Standard vacation provision. The accrual rate is fair and clearly defined.',
      section: 'Section 12',
    },
  ],
};

export const CONTRACT_TYPES = ['MSA', 'Employment', 'NDA', 'Rental', 'TOS', 'Partnership', 'Freelance', 'Other'];

export const RISK_COLORS = {
  safe: { bg: 'var(--safe-bg)', border: 'var(--safe-border)', text: 'var(--safe)', label: 'Safe' },
  caution: { bg: 'var(--caution-bg)', border: 'var(--caution-border)', text: 'var(--caution)', label: 'Caution' },
  unsafe: { bg: 'var(--unsafe-bg)', border: 'var(--unsafe-border)', text: 'var(--unsafe)', label: 'Unsafe' },
};
